# Uncomment any setting that you want to use and modify it
# A label is just an easy way for you to spot this configuration in the dwata UI

# If you have multiple databases/mailchimp/stripe/etc, then use a different label for each of them.
# So you can use multiple databases/services.

# Note: Please DO NOT use spaces in the label names. We recommend lower_case_words_separated_by_underscore

[dwata]
server_host = "localhost"
server_port = 12121


[database.database_one_label]
# db_url = "postgresql://db_user:db_password@db_host/db_name"

[mailchimp.some_label]
# api_key = "api_key"

[stripe.some_label]
# api_key = "api_key"


[database.another_database_label]
# This is a MySQL connection example
# db_url = "mysql://db_user:db_password@db_host/db_name"
# Todo: entire database can be in read only mode
# read_only = False
# Todo: Specify columns that are read only across whole database, use wildcards
# read_only_columns = ["email", "*_email"]
# Todo: Hidden columns are not available unless you explicitly add in from query editor
# These are columns that are hidden across the database
# hidden_columns = []
# System tables are always read-only and their names are at the bottom of list of tables
system_tables = []
    [database.another_database_label.table_name]
        # Columns that are marked unavailable are not in schema and in any API calls
        # Columns that are named `password`, `secret` are automatically unavailable
        unavailable_columns = ["email"]

        # Todo: entire table can be in read only mode
        # read_only = True
        # Todo: Specify columns that are read only
        # read_only_columns = ["email"]
        # Todo: Hidden columns are not available unless you explicitly add in from query editor
        # hidden_columns = []


[mailchimp.another_mailchimp_account_label]
# api_key = "api_key"
